name: C/C++ CI

on:
  push:
    branches: 
    - master
    - 'development/*'
  pull_request:
    branches: 
    - master
    - 'development/*'

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Checkout submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --recursive
      
    - name: Build sources
      run: |
        mkdir build && cd build
        cmake ..
        make

    - name: Run Unit Tests
      if: ${{ success() }}
      run: |
        cd build
        ./unit_test

